{
 "/api/2.0/accounts/{account_id}/credentials/{credentials_id}": {
  "get": {
   "operationId": "credentials-get",
   "externalDocs": {
    "url": "https://docs.databricks.com/api/account/credentials/get"
   },
   "x-stackQL-resource": "credentials",
   "x-stackQL-method": "get",
   "x-stackQL-verb": "select",
   "x-numReqParams": 2,
   "parameters": [
    {
     "name": "account_id",
     "required": true,
     "description": "uuid",
     "in": "path"
    },
    {
     "name": "credentials_id",
     "required": true,
     "description": "uuid",
     "in": "path"
    }
   ],
   "responses": {
    "200": {
     "description": "The credential configuration was successfully returned.",
     "content": {
      "application/json": {
       "schema": {
        "type": "object",
        "properties": {
         "credentials_id": {
          "type": "string"
         },
         "credentials_name": {
          "type": "string"
         },
         "aws_credentials": {
          "type": "object",
          "properties": {
           "sts_role": {
            "type": "object",
            "properties": {
             "role_arn": {
              "type": "string"
             },
             "external_id": {
              "type": "string"
             }
            }
           }
          }
         },
         "account_id": {
          "type": "string"
         },
         "creation_time": {
          "type": "integer"
         }
        }
       }
      }
     }
    },
    "401": {
     "description": "The request does not have valid authentication credentials for the operation."
    },
    "404": {
     "description": "Operation was performed on a resource that does not exist."
    },
    "500": {
     "description": "Internal error."
    }
   },
   "description": "Gets a Databricks credential configuration object for an account, both specified by ID."
  }
 }
}